apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - ngo-service.yaml
  - donation-service.yaml
  - volunteer-service.yaml

commonLabels:
  project: solidarytech
  managed-by: argocd
