site_name: SolidaryTech — Hackathon Fase 5
site_description: Documentação técnica do projeto SolidaryTech (POSTECH DCLT — Fase 5)
site_author: Juliano da Silva Lopes

theme:
  name: material
  language: pt-BR
  logo: assets/images/logo.png
  favicon: assets/images/logo.png
  # Paleta de cores moderna (Indigo e Teal)
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: cyan
      accent: teal
      toggle:
        icon: material/weather-sunny
        name: Mudar para modo escuro
    # Configuração para o modo Escuro
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: cyan
      accent: teal
      toggle:
        icon: material/weather-night
        name: Mudar para modo claro
  features:
    - navigation.tabs
    - navigation.top
    - navigation.sections
    - content.code.copy
    - toc.integrate
    - search.suggest            # Autocompletar inteligente na busca
    - search.highlight

nav:
  - Início: index.md
  - Cronograma: cronograma.md
  - Fundação DevOps: 00-fundacao-devops.md
  - SRE: 01-sre.md
  - FinOps: 02-finops.md
  - ITSM e AIOps: 03-itsm-aiops.md
  - DR e Segurança: 04-dr-seguranca.md

markdown_extensions:
  - admonition
  - tables
  - toc:
      permalink: true
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.details
  - attr_list
  - pymdownx.tabbed:
      alternate_style: true 
