# Lab: limites menores para caber em nós menores
- op: replace
  path: /spec/template/spec/containers/0/resources
  value:
    requests: { cpu: "50m",  memory: "64Mi"  }
    limits:   { cpu: "100m", memory: "128Mi" }
  target:
    kind: Deployment
    name: ngo-service
- op: replace
  path: /spec/template/spec/containers/0/resources
  value:
    requests: { cpu: "100m", memory: "128Mi" }
    limits:   { cpu: "250m", memory: "256Mi" }
  target:
    kind: Deployment
    name: donation-service
